"""
Test functions for the create_csv.py script.
"""

import os
import csv
from create_csv import analyze_image, write_to_csv

def test_analyze_image_none():
    """
    Test that analyze_image returns an empty dictionary of joints when an
    invalid image name is given.
    """
    nonexistant_image = "not_an_image.png"
    assert analyze_image(nonexistant_image) == {}

def test_analyze_image_keys_size():
    """
    Test that when a correct image is given, the returned joint_positions
    dictionary correctly has 18 joint keys.
    """
    test_image_name = "first_mask"
    assert len(analyze_image(test_image_name).keys()) == 18

def test_analyze_image_values():
    """
    Test that when a correct image is given, the returned joint_positions all
    have 2 valued lists as the values in the dictionary and each of those
    values are within the bounds of the inputted image pixel size.
    """
    test_image_name = "first_mask"
    test_joint_positions = analyze_image(test_image_name)
    for _, value in test_joint_positions.items():
        # each value in joint_positions should be 2-entries
        if len(value) != 2:
            assert False
        # each of the two entries should be inside of a 480x640 image
        if value[0] < -1 or value[0] > 640 or value[1] < -1 or value[1] > 480:
            assert False
    assert True

def test_write_to_csv_exists():
    """
    Test that the write_to_csv function correctly creates a csv that is the
    same name as the inputted csv_name.
    """
    test_joint_positions = {}
    test_csv_name = "test"
    write_to_csv(test_csv_name, test_joint_positions)
    csv_exists = os.path.exists(f'mask_joint_positions/{test_csv_name}.csv')
    # file deleted to ensure a clean workspace
    if csv_exists:
        os.remove(f'mask_joint_positions/{test_csv_name}.csv')
    assert csv_exists

def test_write_to_csv_no_joints():
    """
    Test that the write_to_csv function correctly creates an empty csv of the
    inputted name when an empty joint_positions dictionary is inputted.
    """
    test_joint_positions = {}
    test_csv_name = "test"
    write_to_csv(test_csv_name, test_joint_positions)
    with open(f'mask_joint_positions/{test_csv_name}.csv', 'r') as csv_file:
        csv_reader = csv.reader(csv_file)
        row_count = sum(1 for row in csv_reader)
    os.remove(f'mask_joint_positions/{test_csv_name}.csv')
    assert row_count == 0

def test_write_to_csv_one_joint():
    """
    Test that the write_to_csv function correctly creates a csv of the inputted
    name with only one row, corresponding to the one joint inputted through the
    joint_positions dictionary.
    """
    test_joint_positions = {'0': [0, 0]}
    test_csv_name = "test"
    write_to_csv(test_csv_name, test_joint_positions)
    with open(f'mask_joint_positions/{test_csv_name}.csv', 'r') as csv_file:
        csv_reader = csv.reader(csv_file)
        # sum reach row in the csv file
        row_count = sum(1 for _ in csv_reader)
    # file deleted to ensure a clean workspace
    os.remove(f'mask_joint_positions/{test_csv_name}.csv')
    assert row_count == 1

def test_write_to_csv_one_joint_values():
    """
    Test that the value in the csv generated by write_to_csv correctly stores
    the inputted joint_positions dictionary.
    """
    test_joint_positions = {'0': [0, 0]}
    test_csv_name = "test"
    write_to_csv(test_csv_name, test_joint_positions)
    with open(f'mask_joint_positions/{test_csv_name}.csv', 'r') as csv_file:
        csv_reader = csv.reader(csv_file)
        joint_counter = 0
        for row in csv_reader:
            # check to make sure each row in the csv equals to inputted
            # dictionary values
            if row[0] != str(joint_counter) or row[1] !=\
                str(test_joint_positions[str(joint_counter)][0]) or\
                row[2] != str(test_joint_positions[str(joint_counter)][1]):
                assert False
            joint_counter += 1
    # file deleted to ensure a clean workspace
    os.remove(f'mask_joint_positions/{test_csv_name}.csv')
    assert True

def test_write_to_csv_eighteen_joints():
    """
    Test that the write_to_csv function correctly creates a csv of the inputted
    name with eighteen row, corresponding to the eighteen joint inputted
    through the joint_positions dictionary.
    """
    test_joint_positions = analyze_image('first_mask')
    test_csv_name = "test"
    write_to_csv(test_csv_name, test_joint_positions)
    with open(f'mask_joint_positions/{test_csv_name}.csv', 'r') as csv_file:
        csv_reader = csv.reader(csv_file)
        row_count = sum(1 for row in csv_reader)
    # file deleted to ensure a clean workspace
    os.remove(f'mask_joint_positions/{test_csv_name}.csv')
    assert row_count == 18

def test_write_to_csv_eighteen_joint_values():
    """
    Test that the value in the csv generated by write_to_csv correctly stores
    the inputted joint_positions dictionary.
    """
    test_joint_positions = analyze_image('first_mask')
    test_csv_name = "test"
    write_to_csv(test_csv_name, test_joint_positions)
    with open(f'mask_joint_positions/{test_csv_name}.csv', 'r') as csv_file:
        csv_reader = csv.reader(csv_file)
        joint_counter = 0
        for row in csv_reader:
            if row[0] != str(joint_counter) or row[1] !=\
                str(test_joint_positions[str(joint_counter)][0]) or\
                row[2] != str(test_joint_positions[str(joint_counter)][1]):
                assert False
            joint_counter += 1
    # file deleted to ensure a clean workspace
    os.remove(f'mask_joint_positions/{test_csv_name}.csv')
    assert True
